# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# Do on startup
# exec-once = $terminal
exec-once = thunar --daemon
exec-once = systemctl --user start hyprpolkitagent
exec-once = waybar
#exec-once = waypaper --restore
exec-once = swww-daemon
exec-once = nm-applet --indicator & blueman-applet &
exec-once = kwalletd6
#exec-once = swaync --indicator
exec-once = wl-paste --type text --watch cliphist store		 # Stores only text data
exec-once = wl-paste --type image --watch cliphist store	 # Stores only image data

# Do after some time
exec-once = /usr/libexec/polkit-kde-authentication-agent-1
exec-once = sleep 3 && mega-sync

# On every reload
exec = hyprctl switchxkblayout all 1
