# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# Do on startup
# exec-once = $terminal
exec-once = systemctl --user start hyprpolkitagent
exec-once = waybar
exec-once = waypaper --restore
exec-once = nm-applet --indicator & blueman-applet &
exec-once = kwalletd6
#exec-once = swaync --indicator

# Do after some time
exec-once = sleep 3 && flatpak run org.easycoding.TunedSwitcher
exec-once = /usr/libexec/polkit-kde-authentication-agent-1
#exec-once = sleep 3 && megasync
exec-once = sleep 1 && hyprctl keyboard_layout cz
