# See https://wiki.hyprland.org/Configuring/Environment-variables/

# Mouse cursor settings
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# QT theme settings
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_QPA_PLATFORMTHEME,qt6ct
#env = QT_STYLE_OVERRIDE,kvantum-dark

# Use wayland where possible
env = OZONE_PLATFORM,wayland
env = MOZ_ENABLE_WAYLAND,1
env = QT_QPA_PLATFORM,wayland

# Auth for ntfy (notification platform)
env = NTFY_TOKEN,tk_gx2ptnojw11eyphdat81tco2vnmyv