# https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = cz,us
    kb_variant =
    kb_model =
    kb_options = grp:win_space_toggle
    kb_rules =
    numlock_by_default = true

# This should be normally 1, but Fusion360 is retarded, so 0 for now.
    follow_mouse = 1

    sensitivity = -0.5 # -1.0 - 1.0, 0 means no modification.
    accel_profile = flat

    touchpad {
        natural_scroll = true
        scroll_factor = 0.50
    }
}

# https://wiki.hyprland.org/Configuring/Variables/#gestures
gestures {
    #workspace_swipe = on	# deprecated
    workspace_swipe_distance = 200
    workspace_swipe_forever = false
    gesture = 3, horizontal, workspace
    gesture = 3, vertical, fullscreen
    workspace_swipe_use_r = true
}

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
device { # Bluetooth mouse eternico
    name = aet-ms480bbt1-mouse
    sensitivity = -0.5
}

device { # Build in touchpad
    name = syna3109:00-06cb:cea3-touchpad
    sensitivity = 0
}
device { # Build in touchpad - lenovo yoga
    name = elan06fa:00-04f3:3293-touchpad
    sensitivity = 0
}

